/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <gpiodriver.h>
#include <stm32f407xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
/* ************************************************
 * MACROS
 * *********************************************** */


/* ************************************************
 * Global Structures
 * *********************************************** */

GPIO_Handler_t orangeLED;

int main(void)
{
	memset(&orangeLED, 0, sizeof(GPIO_Handler_t));

	// Enable Clock for Port D
	GPIO_CLKControl(GPIOD, ENABLE);

	orangeLED.pGPIOBaseAddr = GPIOD;

	orangeLED.GPIOPinConfig.pinNumber = GPIO_PIN_13;
	orangeLED.GPIOPinConfig.pinMode = GPIO_MODE_OUT;
	orangeLED.GPIOPinConfig.pinOutputType = GPIO_OUTPUT_TYPE_PUSHPULL;
	orangeLED.GPIOPinConfig.pinSpeed = GPIO_OUTPUT_SPEED_MEDIUM;
	orangeLED.GPIOPinConfig.pinPullUpPullDown = GPIO_NO_PULL_UP_DOWN;

	GPIO_Init(&orangeLED);
    /* Loop forever */
	int i;
	for(;;)
	{
		GPIO_TogglePin(GPIOD,orangeLED.GPIOPinConfig.pinNumber);
		for(i=0;i<100000;i++);
	}
}
